Adding the project as a template to work with react-native-community/cli
uCreateit/react-native-innovator pull request #32
Opened 2021-03-12 21:32 UTC by AbdoHema2016

Changing the projects directory structure and adding necessary files to create a project using the react-native-community/cli

2021-03-15 14:09 UTC, ajaykumar97 requested changes

2021-03-15 14:09 UTC, ajaykumar97 commented on template/InnovatorRN/_env
> +IS_PRODUCTION=true
The env vars are supposed to be private and not pushed to the VSC. Please remove the `_env` file.

2021-03-15 14:09 UTC, ajaykumar97 commented on template/InnovatorRN/_env.production
> +IS_PRODUCTION=true
The env vars are supposed to be private. Please remove the `_env.production` file.

2021-03-15 14:09 UTC, ajaykumar97 commented on template/InnovatorRN/_env.staging
> +IS_PRODUCTION=true
The env vars are supposed to be private. Please remove the `_env.staging` file.

2021-03-15 14:09 UTC, ajaykumar97 commented on package.json
> +    "react-native-localization": "^2.1.6"
`react-native-localization` is not needed. Please remove the `dependencies` section from this root level `package.json` file.

2021-03-15 15:35 UTC, AbdoHema2016 commented on template/InnovatorRN/_env
> +IS_PRODUCTION=true
its still not pushed once the app is created they would change into a .env and they r already added on the git ignore, adding them here provide a ready to go example for developer using it

2021-03-15 15:35 UTC, AbdoHema2016 commented on template/InnovatorRN/_env.production
> +IS_PRODUCTION=true
its still not pushed once the app is created they would change into a .env and they r already added on the git ignore, adding them here provide a ready to go example for developer using it

2021-03-16 14:00 UTC, ajaykumar97 commented on template/InnovatorRN/_env.production
> +IS_PRODUCTION=true
Yeah, makes sense. Ultimately these files will be converted into `.env` files and will be ignored as they are added into the `.gitignore`.

2021-03-16 14:23 UTC, merged