ReplaceClassComp - Done
uCreateit/react-native-innovator pull request #33
Opened 2021-03-23 12:30 UTC by p3420a1

Left the AsyncStorageUtil as that package needs to be upgraded. Will change it while upgrading the package.

2021-03-24 13:32 UTC, AbdoHema2016 requested changes

2021-03-24 13:32 UTC, AbdoHema2016 commented on template/InnovatorRN/src/containers/Dashboard/index.js
>    onCrossPress = () => {
this is trying to assign a function to an identifier that hasn't been declared anywhere yet, please add const to the function 
const onCrossPress = ()=>{...}

2021-03-24 13:32 UTC, AbdoHema2016 commented on template/InnovatorRN/src/containers/Dashboard/index.js
> +function DashBoard (props) {
please use the useReducer to get the data u need out of redux store

2021-03-24 13:32 UTC, AbdoHema2016 commented on template/InnovatorRN/src/containers/SignIn/index.js
> +    const {loginRequestAction} = props;
please use useDispatch to dispatch actions instead of calling the action from the props

2021-03-24 13:32 UTC, AbdoHema2016 commented on template/InnovatorRN/src/containers/SignIn/index.js
> +            onPress={onSignInPress}
for the onSignInPress function please add a const to the declaration of the function as well

2021-03-24 13:32 UTC, AbdoHema2016 commented on template/InnovatorRN/src/containers/SignIn/index.js
> +            onPress={onSignUpPress}>
same as above

2021-03-25 06:36 UTC, p3420a1 commented on template/InnovatorRN/src/containers/Dashboard/index.js
>    onCrossPress = () => {
sorry abdo. The second commit didn't go at all. The changes were in that commit

2021-03-25 06:37 UTC, p3420a1 commented on template/InnovatorRN/src/containers/Dashboard/index.js
> +function DashBoard (props) {
sorry abdo. The second commit didn't go at all. The changes were in that commit

2021-03-25 06:37 UTC, p3420a1 commented on template/InnovatorRN/src/containers/SignIn/index.js
> +    const {loginRequestAction} = props;
sorry abdo. The second commit didn't go at all. The changes were in that commit

2021-03-25 06:37 UTC, p3420a1 commented on template/InnovatorRN/src/containers/SignIn/index.js
> +            onPress={onSignInPress}
sorry abdo. The second commit didn't go at all. The changes were in that commit

2021-03-25 06:37 UTC, p3420a1 commented on template/InnovatorRN/src/containers/SignIn/index.js
> +            onPress={onSignUpPress}>
sorry abdo. The second commit didn't go at all. The changes were in that commit

2021-04-27 09:42 UTC, AbdoHema2016 commented
please fix conflicts

2021-04-29 11:15 UTC, merged